#!/usr/bin/env sh

##############################################################################
##
##  Gradle wrapper start script for UNIX, MacOS, and Windows (Cygwin/MSYS)
##
##  This file was generated by the Gradle 'init' task.
##
##  You should check the env vars used, and ensure they're to your liking.
##
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    elif [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    fi
fi

if [ -z "$JAVACMD" ] ; then
    JAVACMD=java
fi

# Determine the location of the Gradle wrapper distribution.
if [ -n "$GRADLE_USER_HOME" ] ; then
    GRADLE_USER_HOME_OPTION="-Dgradle.user.home=$GRADLE_USER_HOME"
fi

# Determine the location of the Gradle wrapper JAR.
APP_NAME=`basename "$0"`
APP_BASE_NAME=`basename "$0" .sh`

# Resolve symlinks and determine the application base directory.
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done

APP_HOME=`dirname "$PRG"`
APP_HOME=`cd "$APP_HOME" ; pwd`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS.
DEFAULT_JVM_OPTS='-Xmx64m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8'

# Execute the Java application.
"$JAVACMD" \
  $GRADLE_OPTS \
  $GRADLE_USER_HOME_OPTION \
  -cp "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  $DEFAULT_JVM_OPTS \
  org.gradle.wrapper.GradleWrapperMain "$@"
